const lightTheme = {
  dark: false,
  colors: {
    background: "#ccc",
    error: "#B00020",
    info: "#2196F3",
    onBackground: "#000",
    onError: "#fff",
    onInfo: "#fff",
    onPrimary: "#fff",
    "on-primary-darken-1": "#fff",
    onSecondary: "#000",
    "on-secondary-darken-1": "#fff",
    onSuccess: "#fff",
    onSurface: "#000",
    onSurfaceVariant: "#EEEEEE",
    onWarning: "#fff",
    primary: "#6200EE",
    "primary-darken-1": "#3700B3",
    secondary: "#03DAC6",
    "secondary-darken-1": "#018786",
    success: "#4CAF50",
    surface: "#FFFFFF",
    surfaceVariant: "#424242",
    warning: "#FB8C00",
  },
};

const darkTheme = {
  dark: true,
  colors: {
    background: "#999",
    error: "#CF6679",
    info: "#2196F3",
    onBackground: "#fff",
    onError: "#fff",
    onInfo: "#fff",
    onPrimary: "#fff",
    "on-primary-darken-1": "#000",
    onSecondary: "#000",
    "on-secondary-darken-1": "#000",
    onSuccess: "#fff",
    onSurface: "#fff",
    onSurfaceVariant: "#424242",
    onWarning: "#fff",
    primary: "#BB86FC",
    "primary-darken-1": "#3700B3",
    secondary: "#03DAC5",
    "secondary-darken-1": "#03DAC5",
    success: "#4CAF50",
    surface: "#212121",
    surfaceVariant: "#BDBDBD",
    warning: "#FB8C00",
  },
};

export { lightTheme, darkTheme };
